### PR TITLE
Add support for WorldGuard 7.

### PR DESCRIPTION
**Pull request by Phoenix616**
Also add jsr305 as a dependency for @Nullable (as WorldGuard doesn't include them anymore and we shouldn't have depended on a dependency's dependency to begin with), also remove the dependency-reduced-pom file

### CODE REVIEW

**Comment by pop4959** [comment]
@Phoenix616 Just made some of the same changes on a fork I've been collaborating on. Did you borrow part of the code? Just out of curiosity; it's not a problem because of how it's licensed anyways.

Also, how active is this fork? Some people have referred me here to look at some of the changes you guys have been making, although lately it looks like not much is going on. If this is still being maintained, perhaps we should work together. (Discord pop4959#1781 if you want to add me there)

**Comment by pop4959** [comment]
Oh also is this fork working on 1.13 yet? Because WorldGuard 7 is meant for 1.13 only. Not sure if that'd be an issue here.

**Comment by Phoenix616** [comment]
@pop4959 Yeah, I took a look at yours for orientation (as I wasn't sure how WG/WE 7 is handling some stuff) so there might be some similarities. And yes, this version should work on 1.13 (at least that's the goal, whether or not everything works I don't know as I haven't tested everything yet on my test server). 
Generally speaking I would say that it is active enough to be used once 1.13 compatibility is ensured (as I want to use it for my server as I'm not really a fan of certain things done in other forks)

**Comment by pop4959** [comment]
@Phoenix616 Sounds good! Updating it was certainly confusing given how much the API was refactored between WG 6 and 7. I've also never used the API before.

I agree that some of the changes in many other forks are bad. Especially in the one I am working on right now, because the previous maintainer made quite a mess before he quit. I like that this fork is kept relatively clean compared to Hidendra's.

Anyways, I wouldn't mind collaborating more with you guys. Especially concerning issues that would be relevant to all such forks of LWC.  I also run a server where LWC is highly important, so any issues that you find, I would also probably find relevant (and vice versa). Definitely feel free to get in touch with me if you want.

**Pull request merged**
