### PR TITLE
Purge with player names and tweak hoppers

### PR DESCRIPTION
**Pull request by trainphreak**
Please excuse the messiness of some of the commits here. I'm not great with Git/Github, so a couple commits involve manually editing in changes from other repos. Also a couple of the commits were made while thinking "whatever, nobody else will ever care about this", so I do apologize for that >.<

There are two main changes in this PR.

1. The /lwc admin purge <player(s)> command now works with player names again. It runs each name given through the UUIDRegistry.getUUID() method, which returns the UUID for the name or a UUID object of the UUID string, which means that UUIDs can still be used with this command.

2. Minebench's fast-hopper-protection option. This allows hoppers to be protected (can't be broken or accessed except with permission), but doesn't check for protections when processing the InventoryMoveItemEvent if a hopper is either pulling items out of or pushing items into an inventory. If fast-hopper-protection is enabled, hoppers should be blacklisted in the config (which they are by default in this PR), so that hoppers can't be placed next to protected blocks that the placing player doesn't have access to.

### CODE REVIEW

**Comment by trainphreak** [comment]
The differences in pom.xml are several soft dependencies that I changed to updated versions (quite a while ago, I'm sure most of them are out of date again).

**Comment by dmulloy2** [comment]
The diff appears a bit janky and appears to also include my commit. Could you rebase on this fork and make the changes again?

**Comment by trainphreak** [comment]
Will do, but since I forked Hidendra's repo (same as you), it's going to involve deleting my repo and reforking from yours. I'm totally fine with doing this, but you should know that will happen because I don't know what deleting the repo will do to this PR.

**Comment by trainphreak** [comment]
Superceded by #2

**Pull request closed without merging**
